[workspace]
edition = "2021"
members = [
    'node',
    'pallets/template',
    'pallets/rmrk-core',
    'pallets/rmrk-equip',
    'pallets/rmrk-market',
    'runtime',
]
[profile.release]
panic = 'unwind'
