version: "3.2"

services:
  dev:
    container_name: rmrk-substrate
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/rmrk-substrate
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/rmrk-substrate/.cargo
    volumes:
      - .:/var/www/rmrk-substrate
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/rmrk-substrate --dev --ws-external"
